"""empty message

Revision ID: 490a3890552f
Revises: c9ea2458dd33
Create Date: 2023-08-23 17:36:40.305262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '490a3890552f'
down_revision = 'c9ea2458dd33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_blocked_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('token_blocked_list')
    # ### end Alembic commands ###
