"""empty message

Revision ID: d5d9db1a4769
Revises: 490a3890552f
Create Date: 2023-08-23 23:12:37.859071

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd5d9db1a4769'
down_revision = '490a3890552f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('token_blocked_list')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_blocked_list',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('token', sa.VARCHAR(length=1000), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='token_blocked_list_pkey'),
    sa.UniqueConstraint('token', name='token_blocked_list_token_key')
    )
    # ### end Alembic commands ###
